//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.13 at 05:26:39 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DD/20100524/DI", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.omg.spec.dd._20100524.di;
